//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.12.25 at 06:07:16 PM UTC 
//


package com.example.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="IDClient" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="Nom" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="Email" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="Téléphone" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "idClient",
    "nom",
    "email",
    "t\u00e9l\u00e9phone"
})
@XmlRootElement(name = "Client")
public class Client {

    @XmlElement(name = "IDClient", required = true)
    protected String idClient;
    @XmlElement(name = "Nom", required = true)
    protected String nom;
    @XmlElement(name = "Email", required = true)
    protected String email;
    @XmlElement(name = "T\u00e9l\u00e9phone", required = true)
    protected String téléphone;

    /**
     * Gets the value of the idClient property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIDClient() {
        return idClient;
    }

    /**
     * Sets the value of the idClient property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIDClient(String value) {
        this.idClient = value;
    }

    /**
     * Gets the value of the nom property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNom() {
        return nom;
    }

    /**
     * Sets the value of the nom property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNom(String value) {
        this.nom = value;
    }

    /**
     * Gets the value of the email property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmail() {
        return email;
    }

    /**
     * Sets the value of the email property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmail(String value) {
        this.email = value;
    }

    /**
     * Gets the value of the téléphone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTéléphone() {
        return téléphone;
    }

    /**
     * Sets the value of the téléphone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTéléphone(String value) {
        this.téléphone = value;
    }

}
