//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.12.25 at 06:07:16 PM UTC 
//


package com.example.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="IDInvoice" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="IDClient" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="Montant" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
 *         &lt;element name="DateEmission" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *         &lt;element name="Statut" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "idInvoice",
    "idClient",
    "montant",
    "dateEmission",
    "statut"
})
@XmlRootElement(name = "Invoice")
public class Invoice {

    @XmlElement(name = "IDInvoice", required = true)
    protected String idInvoice;
    @XmlElement(name = "IDClient", required = true)
    protected String idClient;
    @XmlElement(name = "Montant")
    protected double montant;
    @XmlElement(name = "DateEmission", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar dateEmission;
    @XmlElement(name = "Statut", required = true)
    protected String statut;

    /**
     * Gets the value of the idInvoice property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIDInvoice() {
        return idInvoice;
    }

    /**
     * Sets the value of the idInvoice property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIDInvoice(String value) {
        this.idInvoice = value;
    }

    /**
     * Gets the value of the idClient property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIDClient() {
        return idClient;
    }

    /**
     * Sets the value of the idClient property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIDClient(String value) {
        this.idClient = value;
    }

    /**
     * Gets the value of the montant property.
     * 
     */
    public double getMontant() {
        return montant;
    }

    /**
     * Sets the value of the montant property.
     * 
     */
    public void setMontant(double value) {
        this.montant = value;
    }

    /**
     * Gets the value of the dateEmission property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDateEmission() {
        return dateEmission;
    }

    /**
     * Sets the value of the dateEmission property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDateEmission(XMLGregorianCalendar value) {
        this.dateEmission = value;
    }

    /**
     * Gets the value of the statut property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatut() {
        return statut;
    }

    /**
     * Sets the value of the statut property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatut(String value) {
        this.statut = value;
    }

}
